### ISSUE TITLE
Null object Error while setBackground in ChatActivity

### ISSUE THREAD

**Issue by arashjit** [dimelo/sdk#3]
I have extend the AppCompact Theme in my project. But when call the Chat Activity it gives-

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.childmode/com.dimelo.dimelosdk.main.ChatActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.Toolbar.setBackgroundColor(int)' on a null object reference

**Comment by elhu** [comment]
Hi @arashjit ,

Thanks for bringing this to our attention.
Could you please provide the full stack-trace as well as your gradle files if you can share them?

**Comment by elhu** [comment]
In the absence of response, I'm closing this issue.

For future reference, the repo for the Android SDK is located at https://github.com/dimelo/Dimelo-Android, so any Android-related issue should be created there instead of here.
